name: wystle
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.2
  connectivity_plus: ^2.3.0
  shared_preferences: ^2.0.13
  # flutter_native_splash: ^2.1.6
  # velocity_x: ^3.4.0
  geocoding: ^2.0.4
  location: ^4.4.0
  # google_maps_flutter: ^2.1.4
  flutter_datetime_picker: ^1.5.1
  # date_format: ^2.0.6
  intl_phone_field: ^3.1.0
  app_settings: ^4.1.6
  intl: ^0.17.0
  alt_sms_autofill: ^1.0.0
  pin_code_fields: ^7.4.0
  geolocator: ^8.2.1
  device_info_plus: ^3.2.4
  flutter_map: ^0.14.0
  # http: ^0.13.4
  latlong2: ^0.8.1
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.6
  cached_network_image: ^3.2.0
  flutter_aws_s3_client: ^0.6.0
  shimmer: ^2.0.0
  flutter_pdfview: ^1.2.2
  path_provider: ^2.0.10
  url_launcher: ^6.1.2
  flex_color_scheme: ^5.0.1
  share_plus: ^4.0.4
  sliding_sheet: ^0.5.2
  device_preview: ^1.1.0
  google_place: ^0.4.7
  location_geocoder: ^1.0.5
  image_picker: ^0.8.5+3
  permission_handler: ^9.2.0
  another_flushbar: ^1.10.29
  flutter_map_tappable_polyline: ^3.1.0
  dart_ipify: ^1.1.1
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  firebase_crashlytics: ^2.8.2
  flutter_local_notifications: ^9.6.1
  provider: ^6.0.3
  workmanager: ^0.5.0
  firebase_in_app_messaging: ^0.6.0+16
  firebase_analytics: ^9.1.10
  fluttertoast: ^8.0.9
  flutter_masked_text2: ^0.9.1
  flutter_neumorphic: ^3.2.0
  pay: ^1.0.10
  flutterwave: ^1.0.1
  stop_watch_timer: ^1.5.0
  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  font_awesome_flutter: ^10.1.0
flutter_native_splash:
  android: true
  image: 

  


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
