// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ_Ux-NDjH56AMaezXGorKNR4VuYwZfmY',
    appId: '1:356444014068:web:2a95a0a67900287a1e25a1',
    messagingSenderId: '356444014068',
    projectId: 'wystle-90bdc',
    authDomain: 'wystle-90bdc.firebaseapp.com',
    storageBucket: 'wystle-90bdc.appspot.com',
    measurementId: 'G-40X63DEYGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1rwX8hFVkjSCuhk1iy-A93rkErDErYAY',
    appId: '1:356444014068:android:410ff9d0861a5e071e25a1',
    messagingSenderId: '356444014068',
    projectId: 'wystle-90bdc',
    storageBucket: 'wystle-90bdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADUPiBFqJ52zl8oKCs3F4TgUkG00xHphw',
    appId: '1:356444014068:ios:e89c2550864039481e25a1',
    messagingSenderId: '356444014068',
    projectId: 'wystle-90bdc',
    storageBucket: 'wystle-90bdc.appspot.com',
    iosClientId: '356444014068-9ngadshh2rlgve8p2n93o7cfvkplujrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.wystle',
  );
}
